FROM node:22-bookworm-slim
RUN apt-get update && apt-get install -y --no-install-recommends python3 make g++ && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY package*.json tsconfig.json ./
COPY apps/operator/package.json apps/operator/package.json
COPY packages/core/package.json packages/core/package.json
COPY packages/fiber/package.json packages/fiber/package.json
COPY packages/ckb/package.json packages/ckb/package.json
COPY packages/adapter-sdk/package.json packages/adapter-sdk/package.json
COPY apps/verifier/package.json apps/verifier/package.json
RUN npm install
COPY packages ./packages
COPY apps/operator ./apps/operator
CMD ["npx","tsx","apps/operator/src/index.ts"]
