import { describe, expect, it } from "vitest";
import { ZERO_HASH, ackHash, computeTranscriptRoot, createSessionId, eventHash, finalStateHashFrom, publicKeyFromPrivate, randomPrivateKeyHex, signAck, signEvent, signObject, verifyAck, verifyEvent, verifyObject, verifyTranscript, type Session, type TranscriptExport } from "@eventmesh/core";

describe("EventMesh core", () => {
  const aPriv=randomPrivateKeyHex(), bPriv=randomPrivateKeyHex(); const a=publicKeyFromPrivate(aPriv), b=publicKeyFromPrivate(bPriv);
  const session:Session={sessionId:createSessionId(),protocol:"eventmesh-v0.1",operatorA:a,operatorB:b,operatorAUrl:"http://a.local:4000",operatorBUrl:"http://b.local:4000",createdAt:new Date().toISOString(),expiresAt:new Date(Date.now()+60000).toISOString(),maxEvents:10};
  it("signs and verifies objects",()=>expect(verifyObject(session,signObject(session,aPriv),a)).toBe(true));
  it("rejects wrong signer",()=>expect(verifyObject(session,signObject(session,bPriv),a)).toBe(false));
  it("signs and verifies events",()=>{const e=signEvent({sessionId:session.sessionId,sequence:1,previousHash:ZERO_HASH,type:"WORK",payload:{x:1},sender:a,createdAt:new Date().toISOString()},aPriv);expect(verifyEvent(e)).toBe(true);});
  it("detects event tampering",()=>{const e=signEvent({sessionId:session.sessionId,sequence:1,previousHash:ZERO_HASH,type:"WORK",payload:{x:1},sender:a,createdAt:new Date().toISOString()},aPriv);expect(verifyEvent({...e,payload:{x:2}} as any)).toBe(false);});
  it("signs and verifies ACKs",()=>{const e=signEvent({sessionId:session.sessionId,sequence:1,previousHash:ZERO_HASH,type:"WORK",payload:{},sender:a,createdAt:new Date().toISOString()},aPriv);const ack=signAck({eventHash:e.eventHash,decision:"ACCEPT",operator:b,createdAt:new Date().toISOString()},bPriv);expect(verifyAck(ack)).toBe(true);expect(ack.ackHash).toBe(ackHash({eventHash:e.eventHash,decision:"ACCEPT",operator:b,createdAt:ack.createdAt}));});
  it("builds deterministic transcript roots",()=>{const e=signEvent({sessionId:session.sessionId,sequence:1,previousHash:ZERO_HASH,type:"WORK",payload:{},sender:a,createdAt:new Date().toISOString()},aPriv);const ack=signAck({eventHash:e.eventHash,decision:"ACCEPT",operator:b,createdAt:new Date().toISOString()},bPriv);expect(computeTranscriptRoot([{event:e,ack}])).toBe(computeTranscriptRoot([{event:e,ack}]));});
  it("validates complete transcript",()=>{const e=signEvent({sessionId:session.sessionId,sequence:1,previousHash:ZERO_HASH,type:"WORK",payload:{},sender:a,createdAt:new Date().toISOString()},aPriv);const ack=signAck({eventHash:e.eventHash,decision:"ACCEPT",operator:b,createdAt:new Date().toISOString()},bPriv);const root=computeTranscriptRoot([{event:e,ack}]);const close={sessionId:session.sessionId,eventCount:1,transcriptRoot:root,finalStateHash:finalStateHashFrom({done:true}),fiberPayments:[],closedAt:new Date().toISOString()};const t:TranscriptExport={session:{session,signatureA:signObject(session,aPriv),signatureB:signObject(session,bPriv)},events:[{event:e,ack}],close:{close,signatureA:signObject(close,aPriv),signatureB:signObject(close,bPriv)}};expect(verifyTranscript(t)).toEqual({ok:true,errors:[]});});
  it("rejects broken hash chain",()=>{const e=signEvent({sessionId:session.sessionId,sequence:1,previousHash:`0x${"11".repeat(32)}`,type:"WORK",payload:{},sender:a,createdAt:new Date().toISOString()},aPriv);const ack=signAck({eventHash:e.eventHash,decision:"ACCEPT",operator:b,createdAt:new Date().toISOString()},bPriv);const t:TranscriptExport={session:{session,signatureA:signObject(session,aPriv),signatureB:signObject(session,bPriv)},events:[{event:e,ack}]};expect(verifyTranscript(t).ok).toBe(false);});
});
